"""Build a standalone Worker using the existing Python package catalogue."""
import ast
import json
from pathlib import Path

root = Path(__file__).resolve().parent.parent
names = {'PACKAGES', 'SURVEY_QUESTIONS', 'BUNDLE_LABELS', 'BUNDLE_ORDER', 'SERVICE_LABELS'}
values = {}
for node in ast.parse((root / 'content/packages.py').read_text(encoding='utf-8')).body:
    if isinstance(node, ast.Assign) and isinstance(node.targets[0], ast.Name):
        name = node.targets[0].id
        if name in names:
            values[name] = ast.literal_eval(node.value)
assert values.keys() == names
header = '// Generated by cloudflare/build.py; edit worker-core.mjs and content/packages.py.\n'
header += ''.join(f'const {name} = {json.dumps(value, ensure_ascii=False)};\n' for name, value in values.items())
source = (root / 'cloudflare/worker-core.mjs').read_text(encoding='utf-8')
(root / 'cloudflare/worker.mjs').write_text(header + source, encoding='utf-8')
print('Built cloudflare/worker.mjs')
